version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crawl4ai-postgres
    environment:
      POSTGRES_DB: crawl4ai
      POSTGRES_USER: crawl4ai_user
      POSTGRES_PASSWORD: crawl4ai_password
      POSTGRES_ADMIN_USER: postgres
      POSTGRES_ADMIN_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crawl4ai_user -d crawl4ai"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: crawl4ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: